version: "3.5"

services:
  # ==============================
  # server
  # ==============================

  server:
    image: iaimhigh.me:5000/server
    build: iaimhigh-server
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      servicenet:
        aliases:
          - server.internal

  # ==============================
  # react
  # ==============================

  public:
    image: iaimhigh.me:5000/public
    build: iaimhigh-public
    restart: always
    depends_on:
      - server
    env_file:
     - .env
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      servicenet:
        aliases:
          - public.internal
networks:
  servicenet:
    name: iaimhigh-servicenet
  publicnet:
    name: iaimhigh-publicnet
